name: DyedBackpacks
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加 染色背包 繁體翻譯版.
website: https://github.com/TheBusyBiscuit/DyedBackpacks

main: io.github.thebusybiscuit.dyedbackpacks.DyedBackpacks
depend: [Slimefun]

api-version: 1.13