name: DyedBackpacks
version: ${project.version}
author: TheBusyBiscuit
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit".
website: https://github.com/TheBusyBiscuit/DyedBackpacks

main: io.github.thebusybiscuit.dyedbackpacks.DyedBackpacks
depend: [Slimefun]

api-version: 1.13